### ISSUE TITLE
[Bug] 通过 Docker Compose 启动，mtranserver 自行退出

### ISSUE THREAD

**Issue by CattenLinger** [xxnuo/MTranServer#6]
环境：
- Docker version 26.1.3, build b72abbb
- Ubuntu 22.04.4 LTS
- Intel(R) Xeon(R) CPU E5-2670

在尝试多次启动之后，mtranserver 都自己退出了。

```sh
$> docker compose up
Attaching to mtranserver
mtranserver exited with code 0

$> docker compose up
Attaching to mtranserver
mtranserver exited with code 132
```

没有任何日志内容输出，所以不知道发生了什么。

`docker-compose.yml` 内容：
```yaml
services:
  mtranserver:
    image: xxnuo/mtranserver:latest
    container_name: mtranserver
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - "./data/mtranserver_models:/app/models"
    environment:
      - CORE_API_TOKEN=secret
```

secret 是个随便生成的 UUID，不设置 `CORE_API_TOKEN` 运行结果没有区别。

文件目录结构：
```text
.
├── data
│   └── mtranserver_models
│       └── zhen
│           ├── lex.50.50.zhen.s2t.bin
│           ├── model.zhen.intgemm.alphas.bin
│           └── vocab.zhen.spm
└── docker-compose.yml
```

手动通过 `docker run` 进入容器后执行 `./core`：

```
root@7147d6be2c43:/app# ./core
Illegal instruction (core dumped)
```
